name = "Simplex Support Services"
mainprefix = "z"
prefix = "sss"
author = "Simplex Team"

[files]
include = [
	"mod.cpp",
	"assets/sss.paa",
	"LICENSE",
	"authors.txt"
]

[version]
major = 1
minor = 0
patch = 0
git_hash = 0
